export enum SubCategory {
  // Development
  WEB_DEVELOPMENT = 'Web Development',
  MOBILE_APPS = 'Mobile Apps',
  PROGRAMMING = 'Programming',
  GAME_DEVELOPMENT = 'Game Development',
  DATABASES = 'Databases',
  SOFTWARE_TESTING = 'Software Testing',
  SOFTWARE_ENGINEERING = 'Software Engineering',
  DEVELOPMENT_TOOLS = 'Development Tools',
  ECOMMERCE = 'Ecommerce',

  // IT & Software
  IT_CERTIFICATION = 'IT Certification',
  NETWORK_SECURITY = 'Network & Security',
  HARDWARE = 'Hardware',
  OPERATING_SYSTEMS = 'Operating Systems',
  OTHER_IT_SOFTWARE = 'Other IT & Software',

  // Office Productivity
  MICROSOFT = 'Microsoft',
  APPLE = 'Apple',
  GOOGLE = 'Google',
  SAP = 'SAP',
  INTUIT = 'Intuit',
  SALESFORCE = 'Salesforce',
  ORACLE = 'Oracle',
  OTHER_OFFICE_PRODUCTIVITY = 'Other Office Productivity',

  // Personal Development
  PERSONAL_TRANSFORMATION = 'Personal Transformation',
  LEADERSHIP = 'Leadership',
  PRODUCTIVITY = 'Productivity',
  PERSONAL_FINANCE = 'Personal Finance',
  CAREER_DEVELOPMENT = 'Career Development',
  PARENTING_RELATIONSHIPS = 'Parenting & Relationships',
  HAPPINESS = 'Happiness',
  RELIGION_SPIRITUALITY = 'Religion & Spirituality',
  PERSONAL_BRAND_BUILDING = 'Personal Brand Building',
  CREATIVITY = 'Creativity',
  INFLUENCE = 'Influence',
  SELF_ESTEEM = 'Self Esteem',
  STRESS_MANAGEMENT = 'Stress Management',
  MEMORY_STUDY_SKILLS = 'Memory & Study Skills',
  MOTIVATION = 'Motivation',
  OTHER_PERSONAL_DEVELOPMENT = 'Other Personal Development',

  // Design
  WEB_DESIGN = 'Web Design',
  GRAPHIC_DESIGN = 'Graphic Design',
  DESIGN_TOOLS = 'Design Tools',
  USER_EXPERIENCE = 'User Experience',
  GAME_DESIGN = 'Game Design',
  DESIGN_THINKING = 'Design Thinking',
  ANIMATION_3D = '3D & Animation',
  FASHION_DESIGN = 'Fashion Design',
  ARCHITECTURAL_DESIGN = 'Architectural Design',
  INTERIOR_DESIGN = 'Interior Design',
  OTHER_DESIGN = 'Other Design',

  // Marketing
  DIGITAL_MARKETING = 'Digital Marketing',
  SEARCH_ENGINE_OPTIMIZATION = 'Search Engine Optimization',
  SOCIAL_MEDIA_MARKETING = 'Social Media Marketing',
  BRANDING = 'Branding',
  MARKETING_FUNDAMENTALS = 'Marketing Fundamentals',
  ANALYTICS_AUTOMATION = 'Analytics & Automation',
  PUBLIC_RELATIONS = 'Public Relations',
  ADVERTISING = 'Advertising',
  VIDEO_MOBILE_MARKETING = 'Video & Mobile Marketing',
  CONTENT_MARKETING = 'Content Marketing',
  NON_DIGITAL_MARKETING = 'Non Digital Marketing',
  GROWTH_HACKING = 'Growth Hacking',
  PRODUCT_MARKETING = 'Product Marketing',
  AFFILIATE_MARKETING = 'Affiliate Marketing',
  OTHER_MARKETING = 'Other Marketing',

  // Lifestyle
  ARTS_CRAFTS = 'Arts & Crafts',
  FOOD_BEVERAGES = 'Foods & Beverages',
  BEAUTY_MAKEUP = 'Beauty & Makeup',
  TRAVEL = 'Travel',
  GAMING = 'Gaming',
  HOME_IMPROVEMENT = 'Home Improvement',
  PET_CARE_TRAINING = 'Pet Care & Training',
  OTHER_LIFESTYLE = 'Other Lifestyle',

  // Photography & Video
  DIGITAL_PHOTOGRAPHY = 'Digital Photography',
  PHOTOGRAPHY_FUNDAMENTALS = 'Photography Fundamentals',
  PORTRAITS = 'Portraits',
  LANDSCAPE = 'Landscape',
  BLACK_WHITE = 'Black & White',
  PHOTOGRAPHY_TOOLS = 'Photography Tools',
  MOBILE_PHOTOGRAPHY = 'Mobile Photography',
  TRAVEL_PHOTOGRAPHY = 'Travel Photography',
  COMMERCIAL_PHOTOGRAPHY = 'Commercial Photography',
  WEDDING_PHOTOGRAPHY = 'Wedding Photography',
  WILDLIFE_PHOTOGRAPHY = 'Wildlife Photography',
  PHOTOGRAPHY_VIDEO = 'Video & Design Tools',
  OTHER_PHOTOGRAPHY_VIDEO = 'Other Photography & Video',

  // Health & Fitness
  FITNESS = 'Fitness',
  GENERAL_HEALTH = 'General Health',
  SPORTS = 'Sports',
  NUTRITION = 'Nutrition',
  YOGA = 'Yoga',
  MENTAL_HEALTH = 'Mental Health',
  DIETING = 'Dieting',
  SELF_DEFENSE = 'Self Defense',
  SAFETY_FIRST_AID = 'Safety & First Aid',
  DANCE = 'Dance',
  MEDITATION = 'Meditation',
  OTHER_HEALTH_FITNESS = 'Other Health & Fitness',

  // Teacher & Training
  INSTRUCTIONAL_DESIGN = 'Instructional Design',
  EDUCATIONAL_DEVELOPMENT = 'Educational Development',
  TEACHING_TOOLS = 'Teaching Tools',
  OTHER_TEACHER_TRAINING = 'Other Teacher & Training',

  // Music
  INSTRUMENTS = 'Instruments',
  PRODUCTION = 'Production',
  MUSIC_FUNDAMENTALS = 'Music Fundamentals',
  VOCALS = 'Vocals',
  MUSIC_TECHNIQUES = 'Music Techniques',
  MUSIC_SOFTWARE = 'Music Software',
  OTHER_MUSIC = 'Other Music',

  // Business
  ACCOUNTING = 'Accounting',
  FINANCE = 'Finance',
  MANAGEMENT = 'Management',
  ENTREPRENEURSHIP = 'Entrepreneurship',
  BUSINESS_ANALYTICS = 'Business Analytics',
  HUMAN_RESOURCES = 'Human Resources',
  INTERNATIONAL_BUSINESS = 'International Business',
  OPERATIONS = 'Operations Management',
  PROJECT_MANAGEMENT = 'Project Management',
  SALES = 'Sales',
  STRATEGY = 'Business Strategy',
  SUPPLY_CHAIN = 'Supply Chain Management',
}
